export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <h1>This is layout from Template Testing module</h1>
                {children}
            </body>
        </html>
    )
}
