export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <header style={headerStyle}>HEADER</header>
                {children}
                <footer style={footerStyle}>FOOTER</footer>

            </body>
        </html>
    )
}

const headerStyle: React.CSSProperties = {
    backgroundColor: '#a83246',
    color: '#fff',
    padding: '10px',
    textAlign: 'center',
};

const footerStyle: React.CSSProperties = {
    backgroundColor: '#a83246',
    color: '#fff',
    padding: '10px',
    textAlign: 'center',
    position: 'fixed',
    bottom: 0,
    width: '100%',
};
