export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <h1 style={headerStyle}>Inner</h1>
            {children}
            
        </>
    )
}

const headerStyle: React.CSSProperties = {
    backgroundColor: '#34ebc3', // Change to the desired background color
    color: '#fff', // Change to the desired text color
    padding: '10px',
    textAlign: 'center',
};

const footerStyle: React.CSSProperties = {
    backgroundColor: '#34ebc3', // Change to the desired background color
    color: '#fff', // Change to the desired text color
    padding: '10px',
    textAlign: 'center',
    position: 'fixed',
    bottom: 0,
    width: '100%',
};