
export const metadata = {
    title: 'Register',
    description: 'Generated by Next.js',
}

const Register = () => {
    return (
        <>
            <h1>Register Page</h1>

        </>
    )
}

export default Register