"use client";

import React, { useRef, useEffect } from 'react';


const page = () => {

    const scrollContainerRef = useRef(null); // Create a ref to hold the scroll container

    useEffect(() => {
        const handleScroll = () => {
            const scrollDistance = scrollContainerRef.current.scrollTop; // Access scroll position
            console.log("Scrolled distance:", scrollDistance);

            // Perform actions based on scroll distance, e.g., trigger animations, lazy loading
        };

        scrollContainerRef.current.addEventListener("scroll", handleScroll);

        return () => {
            scrollContainerRef.current.removeEventListener("scroll", handleScroll);
        };
    }, []);

    return (
        <div ref={scrollContainerRef} style={{ overflowY: "scroll", height: "500px" }}>
            
            <h1>Example 3: useRef Hook</h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam metus neque, porta vel ornare id, viverra vel urna. Etiam porta mauris leo. Mauris sagittis justo sed purus aliquet, pulvinar interdum elit lacinia. Ut volutpat nec odio eget dapibus. Sed tincidunt pretium molestie. Vivamus eros augue, placerat ut lacus vitae, dignissim volutpat felis. Donec consectetur tempor massa, luctus mattis nulla luctus a. Nullam vehicula mi tincidunt augue vulputate porta sit amet id nulla. In at interdum dui. Maecenas in nibh sodales, malesuada libero nec, porta nulla. In fermentum, leo sed lobortis egestas, elit lacus laoreet tellus, ut efficitur eros lacus sed ligula. Quisque placerat dignissim lectus, a lacinia ex venenatis nec. Ut mi dolor, pharetra vitae vestibulum eu, imperdiet et quam. Pellentesque mi dolor, condimentum at suscipit vitae, malesuada ut est. Nam vehicula dui non ante feugiat ultricies. Mauris elementum augue fermentum hendrerit commodo.</p>


        </div>
    );
}

export default page